MOUSEKEY_ENABLE     = no     # Mouse keys
RGB_MATRIX_ENABLE   = no
LTO_ENABLE          = yes
COMBO_ENABLE 		= yes
COMMAND_ENABLE      = no
AUTO_SHIFT_ENABLE   = no
TAP_DANCE_ENABLE    = yes
LEADER_ENABLE       = yes
CAPS_WORD_ENABLE = yes
SRC += oneshot.c
SRC += swapper.c
